version: "2"
services:
  interface-dev:
    build: .
    volumes:
    - ./hosts:/srv/www/
    networks:
    - reverse-proxy
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: https@obvu.ru
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
