version: "2"
services:
  interface-dev:
    build: .
    volumes:
    - ./hosts:/srv/www/
    networks:
    - reverse-proxy
    environment:
      VIRTUAL_HOST: ${DOMAINS}
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
